/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CICERO;

import CICERO.Controller.Controller;

public class App {

    public static void main(String[] args) throws Exception {
        Controller controller= new Controller();
        controller.executeProgram();
    }
}